Add Java Keystore manipulation support

diff --git a/bin/certmaker b/bin/certmaker
--- a/bin/certmaker
+++ b/bin/certmaker
@@ -81,7 +81,7 @@
 #
 ###/doc
 cm:guide() {
-cat <<'EOHELP' | less
+cat <<'ENDOFEXTENDEDGUIDE' | less
 CertMaker
 ===========
 
@@ -118,11 +118,11 @@ Sets up a new CA config, and opens an editor; specifically ensure you update the
 
     certmaker new ca
 
-Set up a generic hosts config which will be used as a template for managed hosts
+It is possible to save a password file in plaintext in `$CERTMAKERCONFIG/ca/pass.txt` to allow running in batch mode; treat this with caution.
+
+If your CA is going to be used to centrally manage certificates and keys, set up a generic hosts config which will be used as a template for managed hosts
 
     certmaker quick --edit
-
-It is possible to save a password file in plaintext in `$CERTMAKERCONFIG/ca/pass.txt` to allow running in batch mode; treat this with caution.
 
 
 Centrally managed hosts
@@ -130,17 +130,19 @@ Centrally managed hosts
 
 If you want the CA to manage both keys and certificates for host machines, use these steps. In this scenario, the CA is responsible for creating both the keys and the certificates that will be placed on host machines.
 
-Create a new host profile - you will be prompted to edit it, and will then be given paths to a key and cert file as a result.
+Create a new host profile, specifying the domains to certify for - you will be prompted to edit it, and will then be given paths to a key and cert file as a result.
 
-    certmaker quick myhost
+    certmaker quick myhost DOMAIN ...
 
 Re-run the command any time you want to renew the certificate. You will need to copy the new certificate to the desired host machine to replace the old certificate.
 
+If you want to add new domains, you will need to edit the host config and add them manually, then re-generate the signed certificate:
 
+    certmaker edit myhost
+    certmaker quick myhost
 
 Generic CSR and CA activities
 -----------------------------
-
 
 ###    Target host
 
@@ -153,30 +155,31 @@ Create a configuration for the CSR, and edit it
 
 If you don't already have a key, create one form the config
 
-    certmaker renew key ./myhost.cnf
+    certmaker renew key myhost.cnf
 
 Finally, create the CSR
 
-    certmaker renew csr ./key-file.key ./myhost.cnf
-
+    certmaker renew csr key-file.key myhost.cnf
 
 This will create a CSR file `myhost.csr` to send to the CA
-
 
 
 ###    Certificate Authority
 
 On receipt of a CSR, simply use the `sign csr` command:
 
-    certmaker sign csr CSRFILE [CERTFILE]
+    certmaker sign csr CSRFILE [OUTCERTFILE]
 
 This will generate a certificate file as specified, or with the same base name as the CSR, to send back to the requestor.
 
 
 
+Sub Commands
+============
 
-View a certificate
-------------------
+
+fetch/view - to retrieve and inspect certificates
+-------------------------------------------------
 
 You can inspect the contents of a certificate PEM file (typically a block of base-64 data bounded with `BEGIN` and `END` statements) using
 
@@ -185,7 +188,28 @@ You can inspect the contents of a certificate PEM file (typically a block of bas
 Certificates generated by CertMaker are always PEM files.
 
 
-EOHELP
+
+jks - Java Keystore and PKCS12 store manipulation
+-------------------------------------------------
+
+You can manipulate a Java Key Store or PKCS12 key store using the `jks` subcommand.
+
+
+When transferring a Key and Certificate pair to a Java target, you should hand off a PKCS12 file ratherm than PEM files
+
+    certmaker jks generate -k generatedkeys.p12 -a defaultalias -f KEYFILE
+
+
+You can then load the key into the Java host's keystore using
+
+    certmaker jks add-key -k KEYSTORE -a ALIAS -f generatedkeys.p12
+
+
+You can view a keystore contents using
+
+    certmaker jks view -k KEYSTORE [-a ALIAS]
+
+ENDOFEXTENDEDGUIDE
 }
 ### Certificate Getter Usage:cert-getter
 #
@@ -1456,6 +1480,393 @@ cm:edit:host() {
 
     cm:util:edit "$myhostd/$myhost.cnf"
 }
+#!/bin/bash
+
+##bash-libs: args.sh @ 75ff4139-modified (1.1)
+
+##bash-libs: patterns.sh @ 75ff4139-modified (1.1)
+
+### Useful patterns Usage:bbuild
+#
+# Some useful regex patterns, exported as environment variables.
+#
+# They are not foolproof, and you are encouraged to improve upon them.
+#
+# $PAT_blank - detects whether an entire line is empty or whitespace
+# $PAT_comment - detects whether is a line is a script comment (assumes '#' as the comment marker)
+# $PAT_num - detects whether the string is an integer number in its entirety
+# $PAT_cvar - detects if the string is a valid C variable name
+# $PAT_filename - detects if the string is a safe UNIX or Windows file name;
+#   does not allow presence of whitespace or special characters aside from '_', '.', '-'
+# $PAT_email - simple heuristic to determine whether a string looks like a valid email address
+#
+###/doc
+
+export PAT_blank='^\s*$'
+export PAT_comment='^\s*(#.*)?$'
+export PAT_num='^[0-9]+$'
+export PAT_cvar='^[a-zA-Z_][a-zA-Z0-9_]*$'
+export PAT_filename='^[a-zA-Z0-9_.-]$'
+export PAT_email="$PAT_filename@$PAT_filename.$PAT_cvar"
+
+### args Usage:bbuild
+#
+# An arguments handling utility.
+#
+###/doc
+
+### args:get TOKEN ARGS ... Usage:bbuild
+#
+# Given a TOKEN, find the argument value
+#
+# Typically called with the parent's arguments
+#
+# 	args:get --key "$@"
+# 	args:get -k "$@"
+#
+# If TOKEN is an int, returns the argument at that index (starts at 1, negative numbers count from end backwards)
+#
+# If TOKEN starts with two dashes ("--"), expect the value to be supplied after an equal sign
+#
+# 	--token=desired_value
+#
+# If TOKEN starts with a single dash, and is a letter or a number, expect the value to be the following token
+#
+# 	-t desired_value
+#
+# Returns 1 if could not find anything appropriate.
+#
+###/doc
+
+function args:get {
+    local seek="$1"; shift || :
+
+    if [[ "$seek" =~ $PAT_num ]]; then
+        local arguments=("$@")
+
+        # Get the index starting at 1
+        local n=$((seek-1))
+        # but do not affect wrap-arounds
+        [[ "$n" -ge 0 ]] || n=$((n+1))
+
+        echo "${arguments[$n]}"
+
+    elif [[ "$seek" =~ ^--.+ ]]; then
+        args:get_long "$seek" "$@"
+
+    elif [[ "$seek" =~ ^-[a-zA-Z0-9]$ ]]; then
+        args:get_short "$seek" "$@"
+
+    else
+        return 1
+    fi
+}
+
+function args:get_short {
+    local token="$1"; shift || :
+    while [[ -n "$*" ]]; do
+        local item="$1"; shift || :
+
+        if [[ "$item" = "$token" ]]; then
+            echo "$1"
+            return 0
+        fi
+    done
+    return 1
+}
+
+function args:get_long {
+    local token="$1"; shift || :
+    local tokenpat="^$token=(.*)$"
+
+    for item in "$@"; do
+        if [[ "$item" =~ $tokenpat ]]; then
+            echo "${BASH_REMATCH[1]}"
+            return 0
+        fi
+    done
+    return 1
+}
+
+### args:has TOKEN ARGS ... Usage:bbuild
+#
+# Determines whether TOKEN is present on its own in ARGS
+#
+# Typically called with the parent's arguments
+#
+# 	args:has thing "$@"
+#
+# Returns 0 on success for example
+#
+# 	args:has thing "one" "thing" "or" "another"
+#
+# Returns 1 on failure for example
+#
+# 	args:has thing "one thing" "or another"
+#
+# "one thing" is not a valid match for "thing" as a token.
+#
+###/doc
+
+function args:has {
+    local token="$1"; shift || :
+    for item in "$@"; do
+        if [[ "$token" = "$item" ]]; then
+            return 0
+        fi
+    done
+    return 1
+}
+
+### args:after TOKEN ARGS ... Usage:bbuild
+#
+# Return all tokens after TOKEN via the RETARR_ARGSAFTER
+#
+#    myargs=(one two -- three "four and" five)
+# 	args:after -- "${myargs[@]}"
+#
+# 	for a in "${RETARR_ARGSAFTER}"; do
+# 		echo "$a"
+# 	done
+#
+# The above prints
+#
+# 	three
+# 	four and
+# 	five
+#
+###/doc
+
+function args:after {
+    local token="$1"; shift || :
+    
+    local current_token="$1"; shift || :
+    while [[ "$#" -gt 0 ]] && [[ "$current_token" != "$token" ]]; do
+        current_token="$1"; shift || :
+    done
+
+    RETARR_ARGSAFTER=("$@")
+}
+
+set -euo pipefail
+
+### JKS manipulator Usage:jksm
+#Manipulate a Java Key Store or PKCS12 store using 'keytool' (which has too many options to remember for infrequent use ...)
+#
+#There are typically 3 options to the jks subcommand:
+#
+#-k KEYSTORE : the keystore to operate on
+#-a ALIAS : the alias to use for the operation, where appropriate
+#-f TARGETFILE : the file that will be read from or written to, changing depending on the command
+#
+#
+#certmaker jks generate -k KEYSTORE -a ALIAS
+#
+#    Create a new key store, with a key alias
+#
+#
+#certmaker jks csr -k KEYSTORE -a ALIAS -f CSRFILE
+#
+#    Derive a CSR from the KEYSTORE from the ALIAS entry
+#
+#
+#certmaker jks add-ca -k KEYSTORE -a ALIAS -f CACERT
+#
+#    Add a CA certificate file CACERT to the KEYSTORE under ALIAS
+#
+#
+#certmaker jks add-cert -k KEYSTORE -a ALIAS -f CERT
+#
+#    Add a certificate file CERT to the KEYSTORE under ALIAS
+#
+#
+#certmaker jks add-key -k KEYSTORE -a ALIAS -f KEYFILE
+#
+#    Add a key file KEYFILE to the KEYSTORE under ALIAS
+#
+#    The key file must be either in PEM or PKCS12 format
+#    If in PEM format, a similarly named CER file must accompany it
+#
+#    e.g. "import/application.key" needs a corresponding "import/application.cer" file
+#
+#
+#certmaker jks delete -k KEYSTORE -a ALIAS
+#
+#    Delete an alias ALIAS from the KEYSTORE
+#
+#
+#certmaker jks view -k KEYSTORE [-a ALIAS]
+#
+#    View the contents of the keystore, or optionally the contents under the keystore alias
+###/doc
+
+jks:dispatch() {
+    action="$1"; shift
+
+    case "$action" in
+        generate)
+            jks:gen ;;
+
+        csr)
+            jks:csr ;;
+
+        add-ca)
+            jks:add:cacert ;;
+
+        add-cert)
+            jks:add:cert ;;
+
+        add-key)
+            jks:add:key ;;
+
+        delete)
+            jks:delete ;;
+
+        view)
+            jks:view ;;
+        rename)
+            jks:rename ;;
+
+        *)
+            out:fail "Unknown action '$action'" ;;
+    esac
+}
+
+jks:args() {
+    local flag
+
+    for flag in "$@"
+    do
+        case "$flag" in
+        -k)
+            keystore="$(args:get -k "${SCRIPT_ARGS[@]}")"
+            ;;
+        -f)
+            targetfile="$(args:get -f "${SCRIPT_ARGS[@]}")"
+            ;;
+        -a)
+            ksalias="$(args:get -a "${SCRIPT_ARGS[@]}")"
+            ;;
+
+        esac
+    done
+}
+
+jks:convert_key() {
+    local certfile="${targetfile%.*}.cer"
+    [[ -f "$certfile" ]] || out:fail "You must provide the certificate file as $certfile"
+    out:info "Combining $targetfile and $certfile"
+
+    # FIXME this generates error "unable to write 'random state'" even though output/result looks fine...
+    if [[ -z "${ksalias:-}" ]]; then
+        openssl pkcs12 -export -inkey "$targetfile" -in "$certfile"
+    else
+        openssl pkcs12 -export -inkey "$targetfile" -in "$certfile" -alias "$ksalias"
+    fi
+}
+
+jks:gen() {
+    jks:args -k -a || out:fail "Keystore and Alias are required"
+    jks:args -f || :
+
+    if [[ -z "${targetfile:-}" ]]; then
+        keytool -genkey -alias "$ksalias" -keyalg RSA -keystore "$keystore" -deststoretype pkcs12 # FIXME This is still generateing JKS store??
+    else
+        jks:convert_key > "$keystore" # provided through $targetfile
+    fi
+
+}
+
+jks:csr() {
+    jks:args -k -a -f || out:fail "Keystore, Alias and Output CSR file are required"
+    keytool -certreq -keyalg RSA -alias "$ksalias" -keystore "$keystore" -file "$targetfile"
+}
+
+jks:add:cacert() {
+    jks:args -k -a -f || out:fail "Keystore, Alias and CA cert are required"
+    keytool -import -alias "$ksalias" -keystore "$keystore" -trustcacerts -file "$targetfile"
+}
+
+jks:add:cert() {
+    jks:args -k -a -f || out:fail "Keystore, Alias and Cert are required"
+    keytool -import -alias "$ksalias" -keystore "$keystore" -file "$targetfile"
+}
+
+jks:ensure_pkcs12() {
+    if [[ "$targetfile" =~ \.*\.p12 ]]; then
+        cat "$targetfile"
+
+    elif grep -qP "PRIVATE KEY" "$targetfile"; then
+        out:warn "You provided PEM files - we will create a temporary store in which to put the key and certificate"
+        jks:convert_key
+
+        out:warn "You will be asked for the destination store password (your keystore) and the source store password (the intermediate store) to complete the import."
+    else
+        out:fail "PEM or PKCS12 file required!"
+    fi
+}
+
+jks:cleanup() {
+    if [[ -f "${p12datafile:-}" ]]; then
+        rm "$p12datafile"
+    fi
+}
+
+jks:add:key() {
+    # Annoyingly, keytool needs a PKCS12 store for importing - it can't simply add a key
+    jks:args -k -f || out:fail "Keystore and Key file ({.key + .cer} or .p12) are required"
+
+    trap jks:cleanup EXIT
+
+    p12datafile="$(mktemp XXXX.p12)"
+    jks:ensure_pkcs12 > "$p12datafile" # Should fail on its own here if bad file
+
+    keytool -importkeystore -srckeystore "$p12datafile" -destkeystore "$keystore" -srcstoretype pkcs12
+
+    jks:cleanup
+}
+
+jks:delete() {
+    jks:args -k -a || out:fail "Keystore and Alias are required"
+    keytool -delete -alias "$ksalias" -keystore "$keystore"
+}
+
+jks:view() {
+    jks:args -k || out:fail "Keystore is required"
+    jks:args -a || :
+    if [[ -n "${ksalias:-}" ]]; then
+        keytool -list -alias "$ksalias" -keystore "$keystore"
+
+    else
+        keytool -list -keystore "$keystore"
+    fi
+}
+
+jks:rename() {
+    jks:args -k -a || out:fail "Keystore required ; Alias required as \`oldalias:newalias\`"
+
+    local oldalias="${ksalias%:*}"
+    local newalias="${ksalias#*:}"
+
+    out:warn "We'll clone the old alias to a new name, then delete the old alias."
+    ( set -ex
+        keytool -keyclone -alias "$oldalias" -dest "$newalias" -keystore "$keystore"
+        keytool -delete -alias "$oldalias" -keystore "$keystore"
+    )
+}
+
+jksm:main() {
+    if [[ -z "$*" ]] || [[ "$*" =~ --help ]]; then
+        autohelp:print jksm
+        exit
+    fi
+
+    bincheck:has keytool || out:fail "'keytool' is not installed - try installing openjdk-8-jre-headless"
+    bincheck:has openssl || out:warn "'openssl' is not installed - key conversions will fail"
+
+    SCRIPT_ARGS=("$@")
+    jks:dispatch "$@"
+}
 
 cm:main() {
     # Do not autohelp:check here, as it would override sub-topic help
@@ -1465,9 +1876,14 @@ cm:main() {
     }
     action="$1"; shift || :
 
+    # Config-less modules
     case "$action" in
         view|fetch)
             cert-getter:main "$action" "$@"
+            return
+            ;;
+        jks)
+            jksm:main "$@"
             return
             ;;
         help|--help)
@@ -1477,7 +1893,6 @@ cm:main() {
     esac
 
     cm:config:load_config
-
     cm:checkuser
 
     case "$action" in
