add template fetching

diff --git a/bin/certmaker b/bin/certmaker
--- a/bin/certmaker
+++ b/bin/certmaker
@@ -6,22 +6,36 @@
 #
 # Create a new CA:
 #
-# 	certmaker new ca CONFFILE
+#     certmaker new ca CONFFILE
 #
 # Create a new host profile:
 #
-# 	certmaker new host HOST
+#     certmaker new host HOST
 #
 # Sign a named host:
 #
-# 	certmaker sign HOST
+#     certmaker sign HOST
 #
 # Sign a CSR:
 #
-# 	certmaker sign CSRFILE
+#     certmaker sign CSRFILE
 #
 ###/doc
 
+##bash-libs: safe.sh @ 75ff4139 (1.1)
+
+### Safe mode Usage:bbuild
+#
+# Set safe mode options
+#
+# * Script bails on error
+# * Accessing a variable that is not set is an error
+# * If a file glob does not expand, cause an error condition
+# * If a component of a pipe fails, the entire pipe is a failure
+#
+###/doc
+
+set -eufo pipefail
 ##bash-libs: autohelp.sh @ 75ff4139 (1.1)
 
 ### autohelp:print [ SECTION [FILE] ] Usage:bbuild
@@ -515,7 +529,7 @@ vars:require() {
 
 CERTMAKER_confpaths=".:$HOME/.config/certmaker:/etc/certmaker"
 
-ctconf:load_config() {
+cm:config:load_config() {
 	local conffile="$(searchpaths:file_from "$CERTMAKER_confpaths" certmaker.config)"
 
 	if [[ -z "$conffile" ]]; then
@@ -523,46 +537,72 @@ ctconf:load_config() {
 	fi
 
 	. "$conffile"
-
-	ctconf:verify
 }
 
-ctconf:verify() {
-	# Most basic required configurations
-	vars:require castore certhosts
+cm:config:get_temp() {
+    echo "$cnftemplates/$1.cnf"
+}
+
+cm:template() {
+    local fromfile
+    local target="$1"; shift
+    local outfile="${1:-}"; shift || :
+
+    case "$target" in
+    ca|host)
+        fromfile="$(cm:config:get_temp "$target")"
+        [[ -n "${outfile:-}" ]] || outfile="./$(basename "$fromfile")"
+
+        sed "
+        s|%CASTOREDIR%|$castore|
+        " "$fromfile" > "$outfile"
+        echo "New template in $outfile"
+        ;;
+    *)
+        out:fail "No template for $target"
+        ;;
+    esac
 }
 
 cm:main() {
-	action="$1"; shift || :
-	# Do not autohelp:check here, as it would override sub-topic help
+    action="$1"; shift || :
+    # Do not autohelp:check here, as it would override sub-topic help
 
-	case "$action" in
-		new)
-			cm:new "$@"
-			;;
-		sign)
-			cm:csr:sign "$@"
-			;;
+    cm:config:load_config
 
-		help)
-			autohelp:print
-			exit 0
-			;;
-		*)
-			autohelp:print
-			out:fail "Unknown action $action"
-			;;
-	esac
+    case "$action" in
+        template)
+            cm:template "$@"
+            ;;
+        new)
+            cm:new "$@"
+            ;;
+        sign)
+            cm:csr:sign "$@"
+            ;;
+
+        help)
+            autohelp:print
+            exit 0
+            ;;
+        view)
+            cm:view "$@"
+            ;;
+        *)
+            autohelp:print
+            out:fail "Unknown action $action"
+            ;;
+    esac
 }
 
 cm:helpcheck() {
-	local section="$1"; shift
+    local section="$1"; shift
 
-	[[ "$*" =~ --help ]] || return 0
+    [[ "$*" =~ --help ]] || return 0
 
-	autohelp:print new-ca
+    autohelp:print new-ca
 
-	exit 0
+    exit 0
 }
 
 cm:main "$@"
